PHYML=phyml
PAUPRAT=pauprat
PAUP=paup
JAVA=java
SCRIPT=script
LIB=lib
PERL=perl -I$(LIB)
DATA=data
RAWDATA=$(DATA)/raw/
SOURCETREES=$(DATA)/sourcetrees
TAXAMAP=$(DATA)/excel/taxa.csv
SPECIESPHYLOXML=$(DATA)/speciestree.xml
FASTAFILES := $(wildcard $(RAWDATA)/*.fas)
CONTREES := $(wildcard $(RAWDATA)/*.tre)
NEXMLFILES := $(wildcard $(SOURCETREES)/*.xml)

# variables for NCBI taxonomy tree
NCBISTEM=phyliptree
NCBITREE=$(DATA)/$(NCBISTEM).phy
NCBIMRP=$(SOURCETREES)/$(NCBISTEM).dat

# variables for supertree
SUPERTREE=$(DATA)/supertree
SUPERMRPSTEM=MRP_matrix
SUPERMRP=$(SUPERTREE)/$(SUPERMRPSTEM).nex
MRPOUTGROUP=mrp_outgroup
RATCHETSETUP=setup.nex
RATCHETCOMMANDS=ratchet.nex
RATCHETCOMMANDSABS=$(SUPERTREE)/$(RATCHETCOMMANDS)
RATCHETRESULT=$(SUPERTREE)/mydata.tre

# these are files that are going to be generated by various targets
PHYLIPFILES = $(patsubst %.fas,%.phylip,$(FASTAFILES))
NEWICKTREES = $(patsubst %.tre,%.dnd,$(CONTREES))
PHYMLTREES  = $(patsubst %.phylip,%.phylip_phyml_tree.txt,$(PHYLIPFILES))
PHYLOXMLGENETREES = $(patsubst %.phylip_phyml_tree.txt,%.phyloxml,$(PHYMLTREES))
MRPMATRICES = $(patsubst %.xml,%.dat,$(NEXMLFILES))
SDITREES = $(patsubst %.phyloxml,%.sdi,$(PHYLOXMLGENETREES))

.PHONY : clean all genetrees speciestree

all : genetrees speciestree sdi

genetrees : $(PHYLIPFILES) $(NEWICKTREES) $(PHYMLTREES) $(PHYLOXMLGENETREES)

speciestree : $(SPECIESPHYLOXML)

sdi : $(SPECIESPHYLOXML) $(PHYLOXMLGENETREES) $(SDITREES)

treebase :
	$(PERL) $(SCRIPT)/fetch_trees.pl -d $(SOURCETREES) -c $(TAXAMAP)

# converts nick's fasta files to phylip files for phyml
$(PHYLIPFILES) : %.phylip : %.fas
	$(PERL) $(SCRIPT)/fas2phylip.pl -i $< -c $(TAXAMAP) > $@

# converts nick's consensus nexus trees to newick trees
$(NEWICKTREES) : %.dnd : %.tre
	$(PERL) $(SCRIPT)/nexus2newick.pl -c $(TAXAMAP) -i $< > $@
	$(PERL) -i $(SCRIPT)/nodelabels.pl $@

# runs phyml
$(PHYMLTREES) : %.phylip_phyml_tree.txt : %.phylip
	$(PHYML) -i $< -u $*.dnd -s BEST

# generates phyloxml trees
$(PHYLOXMLGENETREES) : %.phyloxml : %.phylip_phyml_tree.txt
	$(PERL) $(SCRIPT)/phyloxml.pl -s $* -f newick -c $(TAXAMAP) > $@

# converts downloaded source trees to mrp matrices
$(MRPMATRICES) : %.dat : %.xml
	$(PERL) $(SCRIPT)/treebase2mrp.pl -i $< -f nexml -c $(TAXAMAP) > $@

# converts the NCBI common tree to mrp matrix
$(NCBIMRP) :
	$(PERL) $(SCRIPT)/ncbi2mrp.pl -i $(NCBITREE) -f newick -c $(TAXAMAP) > $@

# concatenates mrp matrices from treebase and ncbi common tree to nexus file
$(SUPERMRP) : $(NCBIMRP) $(MRPMATRICES)
	$(PERL) $(SCRIPT)/concat_tables.pl -d $(SOURCETREES) -c $(TAXAMAP) -o $(MRPOUTGROUP) > $@

# appends command blocks to mrp nexus file
$(RATCHETCOMMANDSABS) : $(SUPERMRP)
	cd $(SUPERTREE) && $(PAUPRAT) $(RATCHETSETUP) && cd -
	$(PERL) $(SCRIPT)/make_ratchet_footer.pl --constraint $(NCBITREE) -f newick -o $(MRPOUTGROUP) --csv $(TAXAMAP) -r $(RATCHETCOMMANDS) >> $(SUPERMRP)

# runs the parsimony ratchet
$(RATCHETRESULT) : $(RATCHETCOMMANDSABS)
	cd $(SUPERTREE) && $(PAUP) $(SUPERMRPSTEM).nex && cd -

# makes consensus species tree in phyloxml format
$(SPECIESPHYLOXML) : $(RATCHETRESULT)
	$(PERL) $(SCRIPT)/make_consensus.pl -i $(RATCHETRESULT) -c $(TAXAMAP) -o $(MRPOUTGROUP) > $@

# runs the sdi analysis
$(SDITREES) : %.sdi : %.phyloxml
	$(JAVA) org.forester.application.sdi $< $(SPECIESPHYLOXML) $@

clean :
	rm -f $(PHYLIPFILES) $(NEWICKTREES) $(PHYMLTREES) $(PHYLOXMLGENETREES) \
        $(MRPMATRICES) $(NCBIMRP) $(RATCHETCOMMANDSABS) $(SUPERMRP) \
        $(RATCHETRESULT) $(SPECIESPHYLOXML) $(SDITREES)