# the following are 3rd party executables you will need to download and install
# http://www.atgc-montpellier.fr/download/binaries/phyml/phyml_v2.4.4.tar.gz
PHYML=phyml
# http://paup.csit.fsu.edu/
PAUP=bin/paup4a125_osx_leopard
# http://mrbayes.sourceforge.net/
MB=mb
# http://abacus.gene.ucl.ac.uk/software/paml.html
CODONML=/Users/rvosa/Applications/paml44/bin/codeml

# these are probably standard, if not you need to install them
JAVA=java
PERL=perl -I$(LIB)

# verbosity for perl logger
VERBOSITY=-v -v -v -v

# standard locations
SCRIPT=script
LIB=lib
DATA=data
RAWDATA=$(DATA)/pythonsequences/
SOURCETREES=$(DATA)/sourcetrees

# important singleton files
TAXAMAP=$(DATA)/excel/taxa.csv
SPECIESLIST=$(DATA)/specieslist.txt
SPECIESPHYLOXML=$(DATA)/speciestree.xml
PAMLRESULT=$(DATA)/pamlresult.txt

RAWFILES := $(wildcard $(RAWDATA)/*.raw)
CONTREES := $(wildcard $(RAWDATA)/*.tre)
NEXMLFILES := $(wildcard $(SOURCETREES)/*.xml)

# variables for MrBayes analysis
MRBAYESBLOCK=$(DATA)/bayesian/commandblock.mb

# variables for NCBI taxonomy tree
NCBISTEM=phyliptree
NCBITREE=$(DATA)/$(NCBISTEM).phy
NCBIMRP=$(SOURCETREES)/$(NCBISTEM).dat

# variables for supertree
SUPERTREE=$(DATA)/supertree
SUPERMRPSTEM=MRP_matrix
SUPERMRP=$(SUPERTREE)/$(SUPERMRPSTEM).nex
MRPOUTGROUP=mrp_outgroup
RATCHETSETUP=setup.nex
RATCHETCOMMANDS=ratchet.nex
RATCHETCOMMANDSABS=$(SUPERTREE)/$(RATCHETCOMMANDS)
RATCHETRESULT=$(SUPERTREE)/mydata.tre
RATCHETFILES=$(SUPERTREE)/mydata.tre $(SUPERTREE)/mydata.tmp $(RATCHETCOMMANDSABS) $(SUPERMRP) $(SUPERTREE)/paupratchet.log

# these are files that are going to be generated by various targets
FASTAFILES   = $(patsubst %.raw,%.fas,$(RAWFILES))
PHYLIPFILES  = $(patsubst %.fas,%.phylip,$(FASTAFILES))
MRBAYESFILES = $(patsubst %.fas,%.mb,$(FASTAFILES))
MCMCTREES    = $(patsubst %.mb,%.mb.con.tre,$(MRBAYESFILES))
NEWICKTREES  = $(patsubst %.tre,%.dnd,$(CONTREES))
PHYMLTREES   = $(patsubst %.phylip,%.phylip_phyml_tree.txt,$(PHYLIPFILES))
COLLAPSEDTREES = $(patsubst %.phylip_phyml_tree.txt,%.ctree,$(PHYMLTREES))
PAMLSEQS     = $(patsubst %.ctree,%.pamlseq,$(COLLAPSEDTREES))
PAMLTREES    = $(patsubst %.ctree,%.pamltree,$(COLLAPSEDTREES))
PAMLCTLS     = $(patsubst %.pamltree,%.pamlctl,$(PAMLTREES))
PAMLOUTS     = $(patsubst %.pamlctl,%.pamlout,$(PAMLCTLS))
PHYLOXMLGENETREES = $(patsubst %.ctree,%.phyloxml,$(COLLAPSEDTREES))
NEXUSFILES = $(patsubst %.ctree,%.nex,$(COLLAPSEDTREES))
SVGFILES = $(patsubst %.nex,%.svg,$(NEXUSFILES))
CSVFILES = $(patsubst %.nex,%.csv,$(NEXUSFILES))
MRPMATRICES = $(patsubst %.xml,%.dat,$(NEXMLFILES))
SDITREES = $(patsubst %.phyloxml,%.sdi,$(PHYLOXMLGENETREES))

.PHONY : clean all genetrees speciestree sdi treebase

all : paml sdi hyphy

fasta : $(FASTAFILES)

mrbayes : $(MCMCTREES)

paml : $(PAMLRESULT)

speciestree : $(SPECIESPHYLOXML)

sdi : $(SPECIESPHYLOXML) $(PHYLOXMLGENETREES) $(SDITREES)

hyphy : $(NEXUSFILES)

treebase :
	$(PERL) $(SCRIPT)/fetch_trees.pl -d $(SOURCETREES) -c $(TAXAMAP) $(VERBOSITY)

specieslist :
	cut -f 3 -d ',' $(TAXAMAP) | sort | uniq > $(SPECIESLIST)

# clean up nick's raw fasta files
$(FASTAFILES) : %.fas : %.raw
	cat $< | $(PERL) $(SCRIPT)/filter_frameshifts.pl -c $(TAXAMAP) \
        | $(PERL) $(SCRIPT)/filter_sparse_codons.pl \
        | $(PERL) $(SCRIPT)/filter_short_seqs.pl -c $(TAXAMAP) -i OPHIHANN -i ANOLCARO \
        | $(PERL) $(SCRIPT)/filter_duplicate_seqs.pl > $@

# converts fasta files to nexus files for mrbayes
$(MRBAYESFILES) : %.mb : %.fas
	$(PERL) $(SCRIPT)/make_mrbayes_data.pl -i $< -c $(TAXAMAP) -s fasta -d dna -m $(MRBAYESBLOCK) > $@

# run mrbayes
$(MCMCTREES) : %.mb.con.tre : %.mb
	$(MB) $<

# run phyml
$(PHYMLTREES) : %.phylip_phyml_tree.txt : %.mb.con.tre
	$(PERL) $(SCRIPT)/fas2phylip.pl -i $*.fas -c $(TAXAMAP) > $*.phylip
	$(PERL) $(SCRIPT)/nexus2newick.pl -i $< > $*.dnd
	$(PHYML) -i $*.phylip -u $*.dnd -s BEST

# collapse monophyletic clades, which are either in-paralogs or multiple
# genbank records for the same locus and the same species
$(COLLAPSEDTREES) : %.ctree : %.phylip_phyml_tree.txt
	$(PERL) $(SCRIPT)/collapse_monophyletic.pl -i $< -f newick -l phylip \
		-c $(TAXAMAP) -s ANOLCARO -s OPHIHANN > $@

# generate trees with labeled internal nodes for PAML codeml
$(PAMLTREES) : %.pamltree : %.ctree
	$(PERL) $(SCRIPT)/make_paml_tree.pl -c $(TAXAMAP) -i $< > $@

# generate PAML's version of phylip files
$(PAMLSEQS) : %.pamlseq : %.ctree
	$(PERL) $(SCRIPT)/make_paml_seqs.pl -i $*.phylip -t $< > $@

# generate paml control files
$(PAMLCTLS) : %.pamlctl : %.pamltree
	$(PERL) $(SCRIPT)/make_paml_ctl.pl -t $< -s $*.pamlseq -o $*.pamlout > $@

# run codonml
$(PAMLOUTS) : %.pamlout : %.pamlctl
	$(CODONML) $<

# parse codonml output
$(PAMLRESULT) : $(PAMLSEQS) $(PAMLOUTS)
	$(PERL) $(SCRIPT)/parse_paml_out.pl $(PAMLOUTS) > $@
	
# generates phyloxml trees
$(PHYLOXMLGENETREES) : %.phyloxml : %.ctree
	$(PERL) $(SCRIPT)/phyloxml.pl -s $* -f newick -c $(TAXAMAP) -e ctree > $@

# generates nexus files
$(NEXUSFILES) : %.nex : %.ctree
	$(PERL) $(SCRIPT)/make_nexus.pl \
        --treefile=$< \
        --treeformat=newick \
        --labels \
        --datafile=$*.phylip \
        --dataformat=phylip \
        --datatype=dna > $@

# generate tree images
$(SVGFILES) : %.svg : %.nex
	$(PERL) $(SCRIPT)/color_branches.pl \
        --csv=$(TAXAMAP) \
        --nexus=$< \
        --hyphy=$*.csv \
        --param=omega3 \
        --verbose \
        --define width=1200 \
        --define height=auto \
        --define format=svg \
        --define shape=rect \
        --define mode=clado \
        --define text_width=300 \
        --define text_vert_offset=8 > $@

# converts downloaded source trees to mrp matrices
$(MRPMATRICES) : %.dat : %.xml
	$(PERL) $(SCRIPT)/treebase2mrp.pl -i $< -f nexml -c $(TAXAMAP) > $@

# converts the NCBI common tree to mrp matrix
$(NCBIMRP) :
	$(PERL) $(SCRIPT)/ncbi2mrp.pl -i $(NCBITREE) -f newick -c $(TAXAMAP) > $@

# concatenates mrp matrices from treebase and ncbi common tree to nexus file
$(SUPERMRP) : $(NCBIMRP) $(MRPMATRICES)
	$(PERL) $(SCRIPT)/concat_tables.pl -d $(SOURCETREES) -c $(TAXAMAP) \
        -o $(MRPOUTGROUP) > $@

# appends command blocks to mrp nexus file
$(RATCHETCOMMANDSABS) : $(SUPERMRP)
	$(PERL) $(SCRIPT)/make_ratchet_commands.pl -s $(RATCHETSETUP) -r 200 -p 15 -m $(SUPERMRP) > $(RATCHETCOMMANDS)
	$(PERL) $(SCRIPT)/make_ratchet_footer.pl --constraint $(NCBITREE) \
        -f newick -o $(MRPOUTGROUP) --csv $(TAXAMAP) -r $(RATCHETCOMMANDS) \
        >> $(SUPERMRP)

# runs the parsimony ratchet
$(RATCHETRESULT) : $(RATCHETCOMMANDSABS)
	cd $(SUPERTREE) && $(PAUP) $(SUPERMRPSTEM).nex && cd -

# makes consensus species tree in phyloxml format
$(SPECIESPHYLOXML) : $(RATCHETRESULT)
	$(PERL) $(SCRIPT)/make_consensus.pl -i $(RATCHETRESULT) -c $(TAXAMAP) \
        -o $(MRPOUTGROUP) > $@

# runs the sdi analysis, this requires that forester.jar is in the $CLASSPATH
$(SDITREES) : %.sdi : %.phyloxml
	$(JAVA) org.forester.application.sdi $< $(SPECIESPHYLOXML) $@

clean :
	rm -f $(FASTAFILES) $(PHYLIPFILES) $(NEWICKTREES) $(PHYMLTREES) \
        $(PHYLOXMLGENETREES) $(MRPMATRICES) $(NCBIMRP) $(RATCHETFILES) \
        $(SPECIESPHYLOXML) $(SDITREES)